### ISSUE TITLE
Mic Recording

### ISSUE THREAD

**Issue by MelJay27** [travc/locbatch#1]
Hi! 
I am curious: When you recorded audio, did you have problems with latency between the start times of the mic recordings?

**Comment by travc** [comment]
Yep.  And the latency varied and wasn't easy to predict.  I was using
hardware which is pretty old now.

We did have a setup which continually recorded to a synchronized ring
buffer where we could tell to start saving data in a latency-free way (or
even a bit backwards in time).  Used it in conjunction with an event
detector to save just the noises we might be interested in.  Worked ok and
wasn't too difficult to implement purely in software assuming the computer
the mics/recorded are connected to is relatively fast.  Ours was an
embedded system though, so the code isn't really portable/useful to others.

**Comment by MelJay27** [comment]
Thanks for the reply! I read your thesis because I am interested in sound localization, but pretty much know nothing about how to approach the issue (just a programmer, not a physicist). I think I can suitably eliminate latency by using a multi-channel interface though, with each microphone being a different channel.
